server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-active: 8
      min-idle: 3
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
